### ISSUE TITLE
make the font setting effect the whole app

### ISSUE THREAD

**Issue by GypsyDangerous** [DisStreamChat/App#13]
Currently the font change only effects the messages and text boxes in a channel page. We want it to change to change the font of the whole app. To do this we need to have that setting change the font family on the top level element and have all children inherit font families

**Comment by akhilkh2000** [comment]
Can you tell me which file this setting is present in and guide me for this as I am a beginner

**Comment by GypsyDangerous** [comment]
in [this](https://github.com/DisStreamChat/App/blob/master/src/index.js) file you would need to add an inline style to the `main` and set the fontFamily to the font in the setting (StreamerInfo)
